{% set version = "1.6.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-soupx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SoupX_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SoupX/SoupX_{{ version }}.tar.gz
  sha256: 2539371ed9e47f5e3c8d86ed6aef155adbe2372a873e225f3b51f1f867f47320

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.0
    - r-matrix
    - r-seurat >=3.2.2
    - r-ggplot2
  run:
    - r-base >=4.0
    - r-matrix
    - r-seurat >=3.2.2
    - r-ggplot2

test:
  commands:
    - $R -e "library('SoupX')"           # [not win]
    - "\"%R%\" -e \"library('SoupX')\""  # [win]

about:
  home: https://github.com/constantAmateur/SoupX
  license: GPL-2.0-only
  summary: Quantify, profile and remove ambient mRNA contamination (the "soup") from droplet based single cell RNA-seq experiments.  Implements the method described in Young et al. (2018) <doi:10.1101/303727>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nh3
